### ISSUE TITLE
[Keccak] Putting all together

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-circuits#105]
Once #103 and #104 are implemented, we have the keccak-f. We need to put them together.

We repeat keccak-f to take different lengths of inputs.
 
Spec: https://hackmd.io/sK7v0lr8Txi1bgION1rRpw#WIP-Circuit-as-a-Lookup-Table

**Comment by CPerezz** [comment]
Closed as it's now tracked under #273
