### ISSUE TITLE
Improvement: consider to optimize range lookups of evm circuit

### ISSUE THREAD

**Issue by DreamWuGit** [appliedzkp/zkevm-circuits#129]
with the adding of more op gadgets, there are multiple range instances for look up:
``` 
// meaningful tags start with 1
    Range256,
    Range32,
    Range17,
    Range16, 
```
we can predicates more will come in as features going to implement,   I am wondering if there is method to mitigate this , such as only have max range  i.e.  Range256, then any range instance less than it can be reduced or removed.  
for example, when need range100 , can utilize Range256 ,maybe with any little additional info to achieve range100 constraint instead of add new range100 to the enum list.

what do you think about it  ?  @han0110 @ChihChengLiang @barryWhiteHat

**Comment by DreamWuGit** [comment]
yeah, agree with future use !

**Comment by ChihChengLiang** [comment]
Looks like this is resolved. Feel free to reopen if you need more discussion.
