### ISSUE TITLE
[bus-mapping] Remove GlobalCounter for `ExecutionStep`s

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#141]
As discussed with @han0110 in the last call, we should only increment the Global Counter for `Operation`s and not also for `ExecutionStep`s (Opcodes) as we're doing now.

So we need to revert that and simply remove the field `gc` from `ExecutionStep`.

**Comment by CPerezz** [comment]
Can we close this @ed255 since the `GlobalCounter` that the `ExecutionStep` holds is not increased and just represents the initial GC of the step operations.

**Comment by spartucus** [comment]
Maybe this is not the right place to ask, there is a question bothers me for a long time: "What's the core difference between `ExecutionStep` and `Operation`, that are used in `load_rw_tables()` and `assign()`? Why not in one struct instead of two?"

sorry to bother you:)

**Comment by CPerezz** [comment]
@spartucus 
An `ExecutionStep` represents an `Opcode` execution within the context of an EVM trace. It contains Memory, Stack, Storage, pc, etc.. and also the operations performed on it.

`Operation`s in that case, are all of the `READ` and `WRITE` operations that have been performed or triggered by an `ExecutionStep` (an opcode basically).

We construct two different structures since while state proof just needs the `Operations` the evm proof needs the `ExecutionStep`s witnesses. And therefore is much easier to witness all of the data and manage it :)

**Comment by spartucus** [comment]
Thanks Carlos!

**Comment by CPerezz** [comment]
Closing this after as discussed with @ed255 is already solved by #162
