### ISSUE TITLE
Move bus-mapping test macros to a crate

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#164]
In [bus-mapping ](https://github.com/appliedzkp/zkevm-circuits/pull/162) we introduced some macros to create eth_types from literals for tests: `address`, `word`, `word_map`.  These macros are only used for testing, but they are used in other crates, not just the bus-mapping.  So ideally we should move them to a crate and then import this crate only as a dev dependency.

**Comment by silathdiir** [comment]
Hi @ed255 , it seems that the macro `address`, `word` and `word_map` have already been moved to [eth-types/src/lib.rs](https://github.com/appliedzkp/zkevm-circuits/blob/main/eth-types/src/lib.rs#L398). Should we move them to a new crate for test?

**Comment by ed255** [comment]
> Hi @ed255 , it seems that the macro `address`, `word` and `word_map` have already been moved to [eth-types/src/lib.rs](https://github.com/appliedzkp/zkevm-circuits/blob/main/eth-types/src/lib.rs#L398). Should we move them to a new crate for test?

Now that these macros are in `eth-types` I think they are better placed than before.  I think that may be good enough, because right now I think adding a crate for three small macros would be overkill.  On the other hand we have the `mock` crate which is only used for testing, but I think it's not very intuitive to put the macros there.  So I'm thinking we can leave these macros in `eth-types` and close this issue.  @silathdiir do you have a different point of view?

**Comment by silathdiir** [comment]
> > Hi @ed255 , it seems that the macro `address`, `word` and `word_map` have already been moved to [eth-types/src/lib.rs](https://github.com/appliedzkp/zkevm-circuits/blob/main/eth-types/src/lib.rs#L398). Should we move them to a new crate for test?
> 
> Now that these macros are in `eth-types` I think they are better placed than before. I think that may be good enough, because right now I think adding a crate for three small macros would be overkill. On the other hand we have the `mock` crate which is only used for testing, but I think it's not very intuitive to put the macros there. So I'm thinking we can leave these macros in `eth-types` and close this issue. @silathdiir do you have a different point of view?

No. Just saw this familiar issue. I think leaving these macros in `eth-types` is good enough for now. We may close this issue. Thanks.
