### ISSUE TITLE
bus-mapping: Add getProof JSON-RPC method from EIP-1186  

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#177]
See: https://eips.ethereum.org/EIPS/eip-1186

As suggested by @ed255 in #171 would be nice to also implement this JSON-RPC method to more or less have a complete set of calls that the bus-mapping requires (for now).

**Comment by spartucus** [comment]
It looks like `web3` added this method several days ago.
https://github.com/tomusdrw/rust-web3/pull/569

**Comment by ed255** [comment]
Resolved in https://github.com/appliedzkp/zkevm-circuits/pull/205
