### ISSUE TITLE
Stop Requiring `Serialize` for some `eth_types` once ethers doesn't require Serialize to work

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#179]
Requiring `Serialize` here is strange; maybe this is an oversight from the ethers-providers crate: to deserialize a json-rpc response it shouldn't require serialize!

_Originally posted by @ed255 in https://github.com/appliedzkp/zkevm-circuits/pull/171#discussion_r751094786_

**Comment by ed255** [comment]
This issue is ready to be resolved because the PR in ethers has been merged already: https://github.com/gakonst/ethers-rs/pull/590

**Comment by ed255** [comment]
> This issue is ready to be resolved because the PR in ethers has been merged already: [gakonst/ethers-rs#590](https://github.com/gakonst/ethers-rs/pull/590)

Actually we need to wait for the next release of ethers in order to import it and resolve this issue.
