### ISSUE TITLE
Keccak: Add padding

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-circuits#203]
### Problem

padding hasn't been speced out and implemented yet.

### Solution

See `digest_from_bytes` from franklin crypto

**Comment by barryWhiteHat** [comment]
Should we also consider applying RLP encoding in the same step ? 

It seems RLP needs to be aware of the length of the message so it can be encode correctly. The padding also needs to be aware of the length so it can be padded correctly. Seems like a place to apply that easily :)

**Comment by barryWhiteHat** [comment]
Ah i think i am wrong above. Keccak does not do RLP for every usecase so its probably good to separate them.

**Comment by ChihChengLiang** [comment]
Current spec here https://hackmd.io/oaZ_rzzET6GP1GG4Y8ojnQ

**Comment by CPerezz** [comment]
Superset by #336
