### ISSUE TITLE
Force all gates to return `[(Cell, F);25]` as state output and recieve as input to copy states between gates

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#219]
Right now we are not always enforcing that the output of a gate is the input of the next one. 
That can obviously lead to witness manipulations from the prover side.

If we actually constrain the outputs of the gates to the inputs of the next ones, this will not happen. This can be done by applying copy constraints between the cells using: ` region.constrain_equal(*cell, new_cell)?;`

We can take as example, `Absorb`, `IotaB9` and `IotaB13`.

**Comment by ChihChengLiang** [comment]
I'll take on the Pi gate and the Rho gate
