### ISSUE TITLE
chore: add Cargo.lock into git 

### ISSUE THREAD

**Issue by lispc** [appliedzkp/zkevm-circuits#231]
This is the recommended way for dealing with Cargo.lock in git.    
<https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries>

So everyone has the exact same deps, reproducing problems will be easier.

It can prevent problems like <https://github.com/appliedzkp/zkevm-circuits/pull/226#issuecomment-994111114>

**Comment by ChihChengLiang** [comment]
closed by #232
