### ISSUE TITLE
Bring back ethers deps to crates.io once a new patch is shipped

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#233]
In https://github.com/appliedzkp/zkevm-circuits/pull/226 we needed to pull all `ethers` deps from git since https://github.com/gakonst/ethers-rs/issues/692 is not yet in crates.io.

Once the new version is up. We should get back to crates.io deps by removing the patches introduced in the workspace `Cargo.toml`.

**Comment by HAOYUatHZ** [comment]
Or use 

```
ethers-providers = { git = "https://github.com/gakonst/ethers-rs" }
```


In this way, the `Cargo.lock` will be updated automatically.

If we don;t want to keep updating to the latest `ethers`, we could also just specify a rev/tag
