### ISSUE TITLE
Question: Must we build this project with Go?

### ISSUE THREAD

**Issue by silathdiir** [appliedzkp/zkevm-circuits#258]
Hi, I found [geth-utils/build.rs](https://github.com/appliedzkp/zkevm-circuits/blob/main/geth-utils/build.rs#L16) when reviewing the code. I am sorry that I have a simple question about `geth-utils`. Is `geth-utils` a necessary member? Could it be disabled with cargo `feature`? Thanks a lot.

**Comment by HAOYUatHZ** [comment]
We need it for `bus_mapping::mock`.

BTW I also notice that build time takes up a considerable part of the CI (5~7min). Think we can use cargo cache (within https://github.com/actions/cache) to speed up the build time? @silathdiir

**Comment by ChihChengLiang** [comment]
@HAOYUatHZ I think caching is a good idea, want to hear from @ed255 or @CPerezz too.

**Comment by CPerezz** [comment]
Sounds nice. 
I worked with cache in GH actions directly and it's a bit messy as only caches 1 branch.

I've never tried the cache action, so we can try it of course.

For me it's a 👍. Let's hear @ed255

**Comment by HAOYUatHZ** [comment]
If all good, I think I can have @silathdiir work on this.

So that yall can focus on circuit codes.

**Comment by CPerezz** [comment]
Would like to get input from @barryWhiteHat and @ed255 .

As said, for me all cool!!!

**Comment by ed255** [comment]
I agree that build times are quite high on the CI!  Caching build artifacts sounds great!

@silathdiir Currently the dependency of go is required for tests, as we are using traces generated by `go-ethereum` to test the circuits and the bus-mapping.  Although in theory this is only required for test, we are also building `geth-utils` in non test mode.  We could change this in the future, so that the go dependency is becomes a dev-dependency, and the project can be built without go.

**Comment by CPerezz** [comment]
I think that with the cache PR merged, we could close this right? @ed255 @HAOYUatHZ

**Comment by HAOYUatHZ** [comment]
> I think that with the cache PR merged, we could close this right? @ed255 @HAOYUatHZ

there's a WIP PR for https://github.com/scroll-tech/zkevm-circuits/issues/61. maybe after that?

**Comment by ed255** [comment]
I think we can close this issue and open a new one that mirrors https://github.com/scroll-tech/zkevm-circuits/issues/61 to set geth-utils (and go) as a dev-dependency.

**Comment by HAOYUatHZ** [comment]
> I think we can close this issue and open a new one that mirrors [scroll-tech#61](https://github.com/scroll-tech/zkevm-circuits/issues/61) to set geth-utils (and go) as a dev-dependency.

sounds good!

**Comment by ed255** [comment]
Closing this issue, with a new issue here to track `Make geth-utils and go a dev-dependency`: https://github.com/appliedzkp/zkevm-circuits/issues/272
