### ISSUE TITLE
bus-mapping: add block coinbase op code 

### ISSUE THREAD

**Issue by DreamWuGit** [appliedzkp/zkevm-circuits#260]
the evm circuit for block coinbase op code added in pr #259 , also need to add bussmapping side correspondingly.

**Comment by DreamWuGit** [comment]
currently such work merging in pr #259  as well now

**Comment by icemelon** [comment]
We can close this issue now @DreamWuGit

**Comment by DreamWuGit** [comment]
closing this issue as https://github.com/appliedzkp/zkevm-circuits/pull/259 merged!
