### ISSUE TITLE
Make geth-utils and go a dev-dependency

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#272]
Currently this project requires geth-utils, which depend on having the go toolchain installed, to build.
But geth-utils is only used for testing, so we could make a small refactor to make geth-utils and go only required for testing (as a dev-dependency).

In the bus-mapping, the external_tracer uses geth-utils.  We may need to move the external_tracer into a crate so that it can be used by other crates only in tests.  Moving the external_tracer into a crate may require some changes in the bus-mapping to avoid circular dependencies (for example, maybe it's necessary to move eth_types into a crate?).

Related: https://github.com/scroll-tech/zkevm-circuits/issues/61

**Comment by silathdiir** [comment]
Hi @ed255 , thanks for really good instruction for this issue.
I found two issues when I try to work on this:

1. Some structs in file `eth_types.rs` contains types of `bus-mapping/evm`. So I move both `eth_types` and `evm_types` to a crate `types` (not good name?). The evm_types does not contain `Opcode` logic which associates more code of bus-mapping.

2. The code `busmapping::mock` is used for tests of both `bus-mapping` and `zkevm-circuits`. I suppose to add a new crate `bus-mapping-mock` which is a dev-dependency of zkevm-circuits. But it seems that there is duplicate code in bus-mapping (for self tests) and bus-mapping-mock (for zkevm-circuits tests).

What do you think? Thanks.

**Comment by ed255** [comment]
> Hi @ed255 , thanks for really good instruction for this issue. I found two issues when I try to work on this:
> 
>     1. Some structs in file `eth_types.rs` contains types of `bus-mapping/evm`. So I move both `eth_types` and `evm_types` to a crate `types` (may be not good name). The evm_types does not contain `Opcode` logic which associates more code of bus-mapping.

This seems reasonable to me!  I think it's ok to have a crate `types` with `eth` and `evm` modules.  Or maybe a different naming could be `eth_types` crate with the eth_types at the root module and `evm` as a submodule, so we have `eth_types` and `eth_types::evm`.  Just some ideas.

>     2. The code `busmapping::mock` is used for tests of both `bus-mapping` and `zkevm-circuits`. I suppose to add a new crate `bus-mapping-mock` which is a dev-dependency of zkevm-circuits. But it seems that there is duplicate code in bus-mapping (for self tests) and bus-mapping-mock (for zkevm-circuits tests).

It makes sense to move `busmapping::mock` outside of the `bus-mapping` because it depends on `geth-utils` and so is only required for testing but is used in multiple crates.  What would be the duplicated code in `bus-mapping` and `bus-mapping-mock`?  `bus-mapping` would import `bus-mapping-mock` as a dev-dependency, so there shouldn't be duplicate code.  Can you give an example?
