### ISSUE TITLE
Require branches to be up to date before merging

### ISSUE THREAD

**Issue by HAOYUatHZ** [appliedzkp/zkevm-circuits#295]
I re-think about it and feel that it's still better to have "Require branches to be up to date before merging".

So that we can avoid recent CI failures in #280 #291 merges. (People are required to sync with the most recent master and re-run CI).

Regarding previous discussions in https://github.com/appliedzkp/zkevm-circuits/pull/251. It's actually simple: you always only need to sync with the most updated master. No need to decide to "rebase on B or C". And both repo maintainer and PR author can easiy do it: either use git command or manually click "Update branch" botton on the page:
![image](https://user-images.githubusercontent.com/37070449/150330764-bb91dd87-1f37-4887-9c6e-00be87ea04f3.png)

then if it causes conflicts we can know immediately and detect&fix before merging

**Comment by ChihChengLiang** [comment]
I think that's update branch resolved the concern of slowing down development in #251. Requiring branches to be up to date sounds good to me. Request one more comment from @ed255.

**Comment by ed255** [comment]
The fact that the reviewer can trigger the branch update resolves my concerns, so enabling this sounds good to me!  @ChihChengLiang I think you have the permission to make this change on the repository right?

**Comment by ChihChengLiang** [comment]
I've configured "Required the branch to be up to date before merging." It requires a specific test to be added, so I added the "Test on ubuntu-latest," which is the one that #291 and #290 [failed](https://github.com/appliedzkp/zkevm-circuits/actions/runs/1722789052) to pass after merged to main.

@HAOYUatHZ Do you think that configuration resolves the issue?

![Screen Shot 2022-01-22 at 11 16 41 AM](https://user-images.githubusercontent.com/3391420/150622862-a74c91f2-7b38-482b-8c3b-ec2f2d82332a.png)

**Comment by HAOYUatHZ** [comment]
> I've configured "Required the branch to be up to date before merging." It requires a specific test to be added, so I added the "Test on ubuntu-latest," which is the one that #291 and #290 [failed](https://github.com/appliedzkp/zkevm-circuits/actions/runs/1722789052) to pass after merged to main.
> 
> @HAOYUatHZ Do you think that configuration resolves the issue?
> 
> ![Screen Shot 2022-01-22 at 11 16 41 AM](https://user-images.githubusercontent.com/3391420/150622862-a74c91f2-7b38-482b-8c3b-ec2f2d82332a.png)

yes. (usually i will add those tests all, but it doesn't really matter in our cases)

**Comment by HAOYUatHZ** [comment]
closed
