### ISSUE TITLE
Bus mapping compression gadget

### ISSUE THREAD

**Issue by therealyingtong** [appliedzkp/zkevm-circuits#3]
Each witnessed bus mapping (of variable length) is compressed into a commitment. The committed bus mapping is passed in to both circuits as public input. The commitments are indexed by `global_counter`.

Within the circuit, we constrain a witnessed bus mapping at a certain `global_counter` to match the public input commitment at that `global_counter`.

Write a gadget to do this for variable-length bus mappings.

**Comment by ChihChengLiang** [comment]
As we now don't handle the bus mapping compression ourselves, the issue can be closed.

Feel free to reopen if we need further discussion on this.
