### ISSUE TITLE
circuit input builder: support multi-step and "virtual" steps

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#309]
Currently the CircuitInputBuilder expects that every geth step corresponds to one circuit step.  This can be seen in the `handle_tx` function, which goes like this:
```py
handle_tx(geth_trace):
  tx = new_tx()
  for geth_step in geth_trace.struct_logs:
    step = new_step()
    state_ref = self.state_ref(step)
    # pre-process (handle *CALL*/CREATE*)
    gen_associated_steps(geth_step.op, state_ref)
    # post-process (handle return)
    tx.steps.push(step)
  self.block.txs.push(tx)
```
The method `gen_associated_steps` takes a `CircuitInputStateRef` which contains the step (which has some fields filled by handle_tx, and the rest of the fields are filled in `gen_associated_steps`.

For multisteps we will need a way to generate multiple steps for a single geth_step, so I think the best way is to leave the step creation to the `gen_associated_steps` implementation.

For this, the following changes would be required:
1. Remove the field `step` from `CircuitInputStateRef`.  Now the `CircuitInputStateRef` lifetime should move from each step, to for each tx.
2. Add helper functions in `CircuitInputStateRef` to create a new `ExecStep`
3. Extend the `Opcode` trait to support two use cases: `GethExecStep` creates 1 `ExecStep`, `GethExecStep` creates N `ExecSteps`

My idea for point 3 is doing something like this:
```rust
pub trait Opcode {
    fn gen_associated_ops_multi(
        state: &mut CircuitInputStateRef,
        next_steps: &[GethExecStep],
    ) -> Result<(), Error> {
        let get_step = next_steps[0];
        let geth_next_step = next_steps.get(1);
        let mut step = state.new_step();
        // Handle *CALL*/*CREATE*
        state.handle_step_call();
        gen_associated_ops(geth_step.op, state, next_steps);
        // Handle return
        state.handle_step_return();
        state.tx.steps.push(step);
    }

    fn gen_associated_ops(
        state: &mut CircuitInputStateRef,
        next_steps: &[GethExecStep],
    ) -> Result<(), Error>;
}
```
That is, add a method `gen_associated_ops_multi` with a default implementation that handles cases for 1 ExecStep, and allow opcodes with multistep to overwrite it and generate multiple steps.  And then `CircuitInputBuilder::handle_tx` calls `gen_associated_ops_multi` for each GethStep.

**Comment by stevenatcrypto** [comment]
Hello, I'd like to fix this issue if no one is working on it. Thanks.
I will also add code for bus-mapping calldatacopy next which depends on this issue.

**Comment by silathdiir** [comment]
Hello, I'd like to fix this issue if no one is working on it.
I will add code for bus-mapping `calldatacopy` next which depends on this issue. Thanks.

**Comment by ed255** [comment]
> Hello, I'd like to fix this issue if no one is working on it. I will add code for bus-mapping `calldatacopy` next which depends on this issue. Thanks.

Sounds great!  You can use this issue to discuss doubts, ideas, proposals about this feature.

Maybe you can work on this issue and the implementation of `CALLDATACOPY` in the bus-mapping in the same PR so that you can already see if the implementation of the multi-step feature in the `CircuitInputBuilder` is working correctly and fulfills the requirements properly.

**Comment by ed255** [comment]
Regarding the "virtual" steps (steps that don't match 1 to 1 with opcodes) I wrote the following task in https://github.com/appliedzkp/zkevm-circuits/issues/222 :

Generalize the output of the CircuitInputBuilder to follow the definition of `ExecutionState`. 
    - For example, this could be done by converting the ExecStep into an enum
      that can be: ExecStep, MultiStep, ErrorStep, VirtualStep.

**Comment by silathdiir** [comment]
> Regarding the "virtual" steps (steps that don't match 1 to 1 with opcodes) I wrote the following task in #222 :
> 
> Generalize the output of the CircuitInputBuilder to follow the definition of `ExecutionState`. - For example, this could be done by converting the ExecStep into an enum that can be: ExecStep, MultiStep, ErrorStep, VirtualStep.

Hi @edd255, according to your above comment, should we fix `ExecStep` to an enum of SingleStep (original ExecStep), MultiStep, ErrorStep and VirtualStep?

It seems that `gen_associated_ops_multi` is useless for trait Opcode if we fix ExecStep to an enum. Thanks.

**Comment by ed255** [comment]
> > Regarding the "virtual" steps (steps that don't match 1 to 1 with opcodes) I wrote the following task in #222 :
> > Generalize the output of the CircuitInputBuilder to follow the definition of `ExecutionState`. - For example, this could be done by converting the ExecStep into an enum that can be: ExecStep, MultiStep, ErrorStep, VirtualStep.
> 
> Hi @ed255, according to your above comment, should we fix `ExecStep` to an enum of SingleStep (original ExecStep), MultiStep, ErrorStep and VirtualStep?

That was a quick example that I thought about, but let me propose a more thoughtful idea:

Currently we have:
```rust
/// An execution step of the EVM.
#[derive(Debug)]
pub struct ExecStep {
    /// The opcode ID
    pub op: OpcodeId,
    /// Program Counter
    pub pc: ProgramCounter,
    /// Stack size
    pub stack_size: usize,
    /// Memory size
    pub memory_size: usize,
    /// Gas left
    pub gas_left: Gas,
    /// Gas cost of the step.  If the error is OutOfGas caused by a "gas uint64
    /// overflow", this value will **not** be the actual Gas cost of the
    /// step.
    pub gas_cost: GasCost,
    /// Call index within the [`Transaction`]
    pub call_index: usize,
    /// The global counter when this step was executed.
    pub rwc: RWCounter,
    /// State Write Counter.  Counter of state write operations in the call
    /// that haven't been reverted yet up to this step.
    pub swc: usize,
    /// The list of references to Operations in the container
    pub bus_mapping_instance: Vec<OperationRef>,
    /// Error generated by this step
    pub error: Option<ExecError>,
}
```
This is actually covering the `EVMExecStep` and `ErrorStep`.  The `EVMExecStep` is expressed by setting the proper value in `op` and setting `error` to `None`.  The `ErrorStep` is expressed by setting the proper value in `op` and setting `error` the `Some(ExecError)`.

So we're missing a way to express `BeginTx`, `EndTx`, `EndBlock` and `CopyToMemory`.  You can already see how inconvenient this is here: https://github.com/appliedzkp/zkevm-circuits/blob/364aa48b02cec6f2bf0781d0cb11f0b1ff541135/zkevm-circuits/src/evm_circuit/witness.rs#L1073

So I would propose to keep `ExecStep` except for the field `op` which would become:
```rust
pub struct ExecStep {
    /// The execution state
    pub exec_state: ExecState,
    // ...
}

pub enum ExecState {
    Op(OpcodeId),
    BeginTx,
    EndTx,
    EndBlock,
    CopyToMemory,
}
```
And if we need more execution states that don't map 1 to 1 to opcodes in the future, we just extend the `ExecState` enum.  What do you think about this approach?

> It seems that we should not add `gen_associated_ops_multi` to trait Opcode if we fix ExecStep to an enum. What do you think? Thanks.

Following the more specific idea I explained above, the `gen_associated_ops_multi` will still be needed because processing steps like `CallDataCopy` will require generating multiple `ExecSteps`.

Let me know if you have any questions!
