### ISSUE TITLE
[state circuit] implement the new spec 

### ISSUE THREAD

**Issue by lispc** [appliedzkp/zkevm-circuits#350]
The new state circuit spec is merged in <https://github.com/appliedzkp/zkevm-specs/pull/118>

State circuit implementation needs to be updated to be consistent with this spec.

Tracking this issue here.

**Comment by lispc** [comment]
close in favor of <https://github.com/appliedzkp/zkevm-circuits/issues/356>

**Comment by Dhole** [comment]
Oh sorry, I hadn't seen this issue when I opened https://github.com/appliedzkp/zkevm-circuits/issues/356
Apologies!

**Comment by ed255** [comment]
Oh sorry, I hadn't seen this issue when I opened https://github.com/appliedzkp/zkevm-circuits/issues/356
Apologies!
