### ISSUE TITLE
Long testing times in Github Actions required for merging PRs

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#351]
Recently the time required for passing all tests in this repository has increased quite noticeably.

I think this comes from adding more circuit implementation of opcodes and their corresponding tests using the `MockProver`.  For example this is a recent test run https://github.com/appliedzkp/zkevm-circuits/runs/5317122616?check_suite_focus=true
which took 37 minutes!

![image](https://user-images.githubusercontent.com/24987329/155572434-6a299ff0-abbb-45be-8356-b87255c4e41e.png)

I think that as we keep adding more opcodes this will only grow and I'm concerned because this can slow down development at the PR stage.

**Comment by ed255** [comment]
Ideas that come to my mind to resolve this:
- Investigate how optimized the `MockProver` is, and if there's any low hanging fruit that can lead to faster runs, work on it.
- Some opcodes have many tests with different inputs.  Reduce to only leave what's necessary if possible.
    - Maybe we could have for each opcode 2-3 basic tests, and some extended tests with a higher variety of inputs that are not run as part of the Github Actions

**Comment by HAOYUatHZ** [comment]
Or alternatively, we can only run tests for codes related to changes?    （I guess it's doable but haven't really looked into it）

1. detect which folders/sub-workspaces are changed
2. only run those tests

We can do that for each "PR", and still do a complete test for "merge".

**Comment by lispc** [comment]
related < https://github.com/scroll-tech/zkevm-circuits/issues/94>

There seems some low hanging fruit, better modify this after new halo2 being merged

**Comment by pinkiebell** [comment]
Another idea, allocating dedicated runners. This can be done more cheaply by using self hosted hardware somewhere or using hetzner/ovh for example. Though I don't know if hardware performance is a problem here. Does someone has running times on bigger hardware for these tests?

**Comment by HAOYUatHZ** [comment]
> Another idea, allocating dedicated runners. This can be done more cheaply by using self hosted hardware somewhere or using hetzner/ovh for example. Though I don't know if hardware performance is a problem here. Does someone has running times on bigger hardware for these tests?

If that's planned, I also suggest we adding https://github.com/mozilla/sccache. From our experience, it can save several minutes for compiling and testing. Github cache action only caches some downloaed manifest, but sccahe further caches some compiled results.

Serveral minutes isn't considerable for current CI so I didn't suggest it. But if we are adding our own machine, it does no harm but only benefits.

**Comment by HAOYUatHZ** [comment]
I guess this issue can be considered stale for now (at least we are not actively looking into it after https://github.com/appliedzkp/zkevm-circuits/pull/354). 

If we want further optimization we can re-open it in the future?

**Comment by ed255** [comment]
> I guess this issue can be considered stale for now (at least we are not actively looking into it after #354).

Correct!  I think we're all happy and comfortable with the current testing times :)

> If we want further optimization we can re-open it in the future?

I agree! Thanks for bringing this up.  I'll close this issue for now.
