### ISSUE TITLE
Split PR runs with different labels to avoid unnedded work/computations in the CI

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#371]
Based on #368, it would be nice to be able to select the benchmarks that we want to run and not to run all of them.

Assume we have a PR where we only modify keccak, we don't want to bench evm or state circuits since they haven't changed at all.

The proposal is to create 3 new labels: `benchmarks: EVM`, `benchmarks: State` and `benchmarks: Keccak` and each one of them will trigger a single circuit benchmark only.

And if we want, we can keep `benchmarks` and rename it to: `benchmarks: ALL` so that we can trigger all the bench runs with a single label.

cc: @AronisAt79

**Comment by AronisAt79** [comment]
Thanks for the proposal @CPerezz , this makes sense. One question; we have a workflow that launches a bench run (EVM) when a halo2 PR is labeled accordingly. Do we want to evaluate halo2 optimizations against evm/state/keccak circuits performance? Or running only against evm should be sufficient?

**Comment by CPerezz** [comment]
That's a good point. EVM circuit should contain a bit of everything that is possible to do with halo2. So might be the best crate to check `halo2` optimizations.

Let's see some opinions from @han0110 @barryWhiteHat

**Comment by barryWhiteHat** [comment]
Longer term it would be good to be able to test against all. But feel don't need to prioritize that for now.

**Comment by CPerezz** [comment]
> Longer term it would be good to be able to test halo2 against all. But feel don't need to prioritize that for now. Because our halo2 optimizations should be pretty generic for the time being. 

But that's something about Halo2's CI right? And in halo2 repo we can enable benchmarks against a generic circuit or the evm one and bench only halo2 there.
Here in zkevm-circuits we just focus on the circuit benches themseleves no? Maybe I'm missing something.

**Comment by barryWhiteHat** [comment]
Right. I was thinking we can also have just keccak bench in zkevm benches just to avoid running many benches. But don't have to worry about that for now.
