### ISSUE TITLE
Depend on `pairing` crate that is reexported from `halo2_proofs`

### ISSUE THREAD

**Issue by kilic** [appliedzkp/zkevm-circuits#375]
`halo2_proofs` [reexports](https://github.com/appliedzkp/halo2/blob/9d3ab0cf7be57a828df6cedb8f58476b483fdde1/halo2_proofs/src/lib.rs#L29) `pairing` create. So we might want to depend what `halo2_proofs` uses for compatibility of traits.

**Comment by CPerezz** [comment]
@kilic do we still want to go forward with this?

**Comment by kilic** [comment]
@CPerezz I think so because there will be many breaking changes in `pairing` side
