### ISSUE TITLE
Update Sload::gen_associated_ops

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#387]
`Sload::gen_associated_ops` was implemented some time ago and is outdated from the current spec, and doesn't match the current sload circuit implementation.

Testing the implementation is blocked by https://github.com/appliedzkp/zkevm-circuits/pull/349

**Comment by CPerezz** [comment]
Closed via https://github.com/appliedzkp/zkevm-circuits/pull/436
