### ISSUE TITLE
Implement Sstore::gen_associated_ops

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#388]
SSTORE circuit implementation PR: https://github.com/appliedzkp/zkevm-circuits/pull/383

Testing the `gen_associated_ops` implementation is blocked by https://github.com/appliedzkp/zkevm-circuits/pull/349

**Comment by CPerezz** [comment]
Closed via https://github.com/appliedzkp/zkevm-circuits/pull/436
