### ISSUE TITLE
[State] Memory subcircuit constraints

### ISSUE THREAD

**Issue by therealyingtong** [appliedzkp/zkevm-circuits#4]
Constraints specified at https://hackmd.io/Nwd0e5AgTVSBWRQlp-Ving?view#Memory-Circuit.

Most of these constraints can be expressed in a single custom gate. However, the ordering constraints (`key > key_prev`, `gc` > `gc_prev`) will likely need a lookup table range constraint.

**Comment by miha-stopar** [comment]
First version of state circuit merged in #ab0b56ca75fdc936ed438b25354a3a08f7b14412.
