### ISSUE TITLE
Init openzeppelin contracts git submodule in integration-tests `run.sh` 

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#421]
Currently the integration test github action is failing at the gen block step because the git submodule with the openzeppelin contracts is not initialized.  We need to make sure that the submodule is pulled in the `gen_block` step in `integration-tests/run.sh`.
Failed integration test https://github.com/appliedzkp/zkevm-circuits/runs/5790140100?check_suite_focus=true

**Comment by HAOYUatHZ** [comment]
in github workflow
```        
run: git submodule update --init --recursive
```

**Comment by CPerezz** [comment]
Also https://github.com/appliedzkp/zkevm-circuits/runs/5814932034?check_suite_focus=true. 
No difference at all in the error :)
