### ISSUE TITLE
proposal: split 3000 line circuit input builder into multi files

### ISSUE THREAD

**Issue by lispc** [appliedzkp/zkevm-circuits#426]

**Comment by lispc** [comment]
And better after some pending PRs merged.   Or else a lot of conflict

**Comment by ed255** [comment]
Thanks for bringing this up!  I feel responsible for this >_<
One idea I had in mind was to move some of the tests to a new file.  For example, there are lots of tests for the discovery of an error kind from a trace that could be put together in a file.  But maybe it's even better if we move the error discovery along with the tests to a new file (to keep tests and implementation of tested function always in the same file).

**Comment by CPerezz** [comment]
I could take this and do a first round of cleanup @ed255 

WDYT?

**Comment by DreamWuGit** [comment]
@CPerezz  can this be closed as PR #482  merged ?

**Comment by lispc** [comment]
Seems yes
