### ISSUE TITLE
Merge the pull requests using squash

### ISSUE THREAD

**Issue by gaswhat** [appliedzkp/zkevm-circuits#43]
I realize that currently we merge the pull requests without squashing. I think this is not a good practice to maintain a collaborative project. The benefit and drawback of merging w/ and w/o squashing:

- If merging PRs without squash, the commit history could become quite messy as many small commits such as fixing typos will all appear in the commit history. It'll be hard to understand what each commit aims to do and commits from different PRs also interleave with each other.
- OTOH, if we merge PRs with squash, each commit has a clear purpose and we can refer back to its original PR and check the comments in the PR. Further, CI can check whether each PRs can pass after merging into the main branch. Many famous open source projects all use this mechanism to manage the PRs from community. 

I'd like to hear from what your thoughts are on this topic. And hope you could take my suggestion.

**Comment by gaswhat** [comment]
cc @han0110 @therealyingtong @miha-stopar @ChihChengLiang @CPerezz

**Comment by miha-stopar** [comment]
I agree, in my previous projects we were always squashing. But we would probably need to target a bit smaller units - we would do this probably anyway as some bigger chunks are coming now just because we are setting up the project.

**Comment by ChihChengLiang** [comment]
I'm happy to squash my commits into meaningful midsize commits. Either way suits me.

**Comment by DreamWuGit** [comment]
good practice to me

**Comment by CPerezz** [comment]
Yep. Works for me too! 

Just to be sure, are we purposing that we squash our commits ourselves so that we have a reasonable number per PR or instead to use GitHub's functionality of Squashing on merge so that we just have a single one per PR?

**Comment by gaswhat** [comment]
@CPerezz @ChihChengLiang 
I think we can just use Github's squash+rebase merging function to save the effort in squashing the commits ourselves.

If you consider certain commit history within a PR is necessary, maybe we should consider breaking this PR into smaller PRs so that we can keep the necessary histories. Also just FYI, the PR ID and link will be shown in the Github's squashed commit so that you can always check the commit history and comments in that PR.

That's just my opinion. Let me know if you agree on this.

**Comment by ChihChengLiang** [comment]
Think we have a consensus on squash merge now. I've disabled the merge and the rebase options for this repo. Feel free to open new issues or start offline conversations if you feel hard to work with the new workflow.
