### ISSUE TITLE
Rename some Ops value and value_prev fields as the names don't identify with bool

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#442]
Still think this is worth a renaming. Ovbiously not part of this PR, so feel free to ignore. But I will raise an issue about this as sounds confusing.

_Originally posted by @CPerezz in https://github.com/appliedzkp/zkevm-circuits/pull/436#discussion_r844858395_

It's really weird that the fields of the struct are called `value` and `value_prev` and the type they have is `bool`. 

I think would be much more clear to call them `has_value`, `had_value_prev` or anything like this. As basically what you expect in `value` or `value_prev` are actual `Word` or `uX` values.

**Comment by CPerezz** [comment]
WDYT @ed255 @han0110 ?

**Comment by han0110** [comment]
Yeah, `value` seems ambiguous for access list operation. Perhaps we can rename it to `is_warm` and `is_warm_prev`?

**Comment by ed255** [comment]
I guess this applies to `TxAccessListAccountOp` and `TxAccessListAccountStorageOp` right?  Using `is_warm` and `is_warm_prev` sounds good to me!

Also I think `AccountDestructedOp` may have the same problem, so the fields of the struct could be renamed to `is_destructed`, `is_destructed_prev`.
