### ISSUE TITLE
Implement `Calldatacopy::gen_associated_ops`

### ISSUE THREAD

**Issue by han0110** [appliedzkp/zkevm-circuits#443]
After #434 is merged, `gen_associated_ops` of `CALLDATACOPY` should be able to be implemented and tested in circuit to unblock #419.

**Comment by icemelon** [comment]
There's already an open PR for this: https://github.com/appliedzkp/zkevm-circuits/pull/402

**Comment by han0110** [comment]
Ah sorry, I mean `CALLDADACOPY`... Let me update the issue.

**Comment by CPerezz** [comment]
Nevermind! Is taken by @roynalnaruto in #449

Will re-assign!

**Comment by ed255** [comment]
https://github.com/appliedzkp/zkevm-circuits/pull/449 is now merged, so I guess we can close this right?

**Comment by roynalnaruto** [comment]
I am not sure if that's a typo in the title? Should that be `CODECOPY`?

Both `CALLDATACOPY` and `CALLDATALOAD` fixes are in progress (should be done by today):
- https://github.com/appliedzkp/zkevm-circuits/pull/450
- https://github.com/appliedzkp/zkevm-circuits/pull/402

**Comment by CPerezz** [comment]
ping @han0110

**Comment by han0110** [comment]
Yes, #450 and #402 resolved this issue (not #449), big thanks to @roynalnaruto!
