### ISSUE TITLE
Reviewer lottery failed

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-circuits#470]
### Problem

Reviewer lottery failed with an error message

```
Error: HttpError: Resource not accessible by integration
```

https://github.com/appliedzkp/zkevm-circuits/runs/6080587668?check_suite_focus=true

### Solution

Might be a permission error. Investigating

**Comment by DreamWuGit** [comment]
also meet this in #481

**Comment by CPerezz** [comment]
Let's remove this. After all the discussions with @ntampakas and @AronisAt79 seems that there's no way on which we can ask automatic reviews to the Scroll team. 

And the solutions that popped up are quite more complex than what is needed.

Let's just ping for reviews to Scroll members and remove this workflow.
