### ISSUE TITLE
Include a `StackPointer` structure included inside of the `ExecutionStep`

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#50]

**Comment by JiangXb-son** [comment]
Do u means what the form should be if the stackPointer structure included in the ExecutionStep?

**Comment by JiangXb-son** [comment]
Did u mean modify the stack structure like memory inside of the ExecutionStep ? 


pub struct ExecutionStep<'a> {
    memory: BTreeMap<MemoryAddress, EvmWord>,
    stack: Vec<EvmWord>, // =>  stack::  *****<stack-pointer value, EvmWord>,
    opcode: Instruction,
    pc: ProgramCounter,
    gc: GlobalCounter,
    bus_mapping_instances: Vec<&'a Target>, // Holds refs to the container with the related mem ops.
}

**Comment by CPerezz** [comment]
What I meant is that we should probably have a wrapper type over the `stack` field of the `ExecutionStep` and it should be able to easily return the `stack_pointer` via a fn which only needs to check the len of the current `stack -1`.

**Comment by spartucus** [comment]
Hey @CPerezz , you mean like this?
https://github.com/Sin7Y/zkevm-circuits/commit/d9e62597cf400977d882b02df38fb59a46f318d5

**Comment by CPerezz** [comment]
Eactly!! Feel fre to make a PR @spartucus !

**Comment by CPerezz** [comment]
> Hey @CPerezz , you mean like this?
> [Sin7Y@d9e6259](https://github.com/Sin7Y/zkevm-circuits/commit/d9e62597cf400977d882b02df38fb59a46f318d5)

Yes, that looks nice!
