### ISSUE TITLE
Wrong position of key and value

### ISSUE THREAD

**Issue by web3moon** [appliedzkp/zkevm-circuits#508]
https://github.com/appliedzkp/zkevm-circuits/blob/818cf2e54e5800d4bc2a88c9cb3963b5616e439e/bus-mapping/src/circuit_input_builder.rs#L96-L106

call_map define here   

    /// Map call_id to (tx_index, call_index) (where tx_index is the index used
    /// in Block.txs and call_index is the index used in Transaction.
    /// calls).
   ` pub(crate) call_map: HashMap<usize, (usize, usize)>`,

**Comment by ed255** [comment]
Hi @web3moon 
Could you clarify exactly what you think is wrong in the code?

The snippet you linked is doing an insert to the call_map with:
- `key`: `call_id`
- `value`: `(tx_index: eth_tx.transaction_index, call_index: 0)`
Where `call_index` is 0 because it's the first call of the tx.

**Comment by web3moon** [comment]
I see that the comment on the call_map definition says that the key of the call_map is defined as tx_index not call_id

**Comment by ed255** [comment]
> I see that the comment on the call_map definition says that the key of the call_map is defined as tx_index not call_id

```
Map call_id to (tx_index, call_index)
```
means that it maps from `call_id` to the tuple `(tx_index, call_index)`

**Comment by web3moon** [comment]
Oh, my bad, sorry.

**Comment by ed255** [comment]
> Oh, my bad, sorry.

No problem! :smiley:
