### ISSUE TITLE
Consider Multi-Step `ExecutionStep`s and how to deal with them

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#52]
Things like `CALLDATACOPY` can return chunks of bytes which force the EVM to return more than one execution step to refer to them.

That may force us to re-think the way on which the `ExecutionStep` is laid down in `bus-mapping`.

**Comment by HAOYUatHZ** [comment]
is it a duplicate of https://github.com/appliedzkp/zkevm-circuits/issues/309?

**Comment by ed255** [comment]
> is it a duplicate of #309?

Yes! Thanks for noticing this :)

I'm closing this issue in favor of https://github.com/appliedzkp/zkevm-circuits/issues/309 which contains more details.
