### ISSUE TITLE
Integrate traces obtained by Geth debug trace feature

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#53]
That will imply data structure changes but we should be able to parse all of the data needed by `zk-evm circuits`.

**Comment by spartucus** [comment]
Hi @CPerezz, do we need executed(traced) bytecodes to prove a contract method call? Or we just need the pre-state and post-state?

**Comment by CPerezz** [comment]
Hey. I'm currently starting to work on this.

I'm not sure I follow your question.
The idea is that we are able to parse the entire trace and generate the operations and bus-mapping instances for each `ExecutionStep`.
Then, we are able to witness on a really easy way the state proof and Evm proof by simply consuming the `ExecutionTrace` instance.

Each `ExecutionStep` represents the new state after the appliance of the previous `Instruction`.

Does that help?

**Comment by spartucus** [comment]
Thanks for your reply.

> The idea is that we are able to parse the entire trace and generate the operations and bus-mapping instances for each ExecutionStep.

You mean 'The entire trace' is all state(old, intermediate, new), and 'generate the operations' is a method's bytecodes?

**Comment by CPerezz** [comment]
I'm not sure I understand what `old, intermediate, new` refers to. We just have states for each Instruction execution, so for each steps.

**Comment by spartucus** [comment]
Thanks! Yeah, that's state for each Instruction execution.
