### ISSUE TITLE
Change internal representation of `MemoryAddress` to `usize`

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#58]
As said by @han0110 :

> was integrating with bus-mapping and found MemoryAddress is implemented in BigUint. I think for a honest prover, probably we >only need usize for that cause once memory usage up to 2**24, the gas is 20x then current block gas limit.
>
>(btw 2**24 is the hard bound for memory address in my mind for now)

This will make the type `Copy` and might enable some optimizations.

**Comment by spartucus** [comment]
Hi @CPerezz, could you review this? https://github.com/Sin7Y/zkevm-circuits/commit/2bc5572a5efcdeff20bd1d44df397997c5dcdc1f

**Comment by CPerezz** [comment]
LGTM. Feel free to open a PR :smile:
