### ISSUE TITLE
benchmark and start to optimise halo2 prover using ZKG polynomial commitment scheme 

### ISSUE THREAD

**Issue by barryWhiteHat** [appliedzkp/zkevm-circuits#60]
https://github.com/appliedzkp/zkevm-circuits/issues/38 we have replaced the halo2 lib with KZG in the verifier. We also have some work to benchmark the prover using ZKG with halo2 lib. 

Our current approach is probably going to result in very large circuits. So setting an upper bound on the proving time for such large circuits would be useful to 

1. De-risk our current architecture choices 
2. Set our expectations around proving times and the cost of running a proving node. 

https://github.com/kilic/halo2/tree/kzg is the branch that contains the KZG polynomial commitments.

**Comment by barryWhiteHat** [comment]
I think its more about getting an idea of what our proving time will be. We know our circuit will be big and are kind of okay with that.

**Comment by TrapdoorHeader** [comment]
The proving time is measured using the circuit in examples/simple-example-2.rs. The circuit is composed by 4 fixed columns and 3 advice columns. One gate (similar with Plonk）is used - one multiply and one add. The row number is defined by 2^K - half of the rows is "add" enabled and half o the rows is "multiply" enabled. 
The proving time is measured on AMD EPYC 7F52 Processor  - 32 core. 
K-8 - 28 ms
K-15 - 630 ms
K-18 - 3.93 s
K-20 - 15.24 s
K-22 -  57.53 s
K-24 - 272.58 s

**Comment by StarLI-Trapdoor** [comment]
K - 26 - 990.47 s

**Comment by TrapdoorHeader** [comment]
K-26 - 990.47 s

**Comment by gaswhat** [comment]
@TrapdoorHeader This measurement is very interesting. Would you mind share your measurement script? I'd love to try it out on the larger circuit.

**Comment by TrapdoorHeader** [comment]
@gaswhat  Apply the patch first.
https://github.com/kilic/halo2/pull/1/commits/846ea9e469c29cf84ca6af45168db44006381094

And using the command to measure the proving period:
K_NUM=18 ./target/release/examples//simple-example-2

Actually, you can use the bench code with the same circuit of benches/plonk.rs. Due to the benching logic, for larger K, the benching runs very long.

**Comment by barryWhiteHat** [comment]
https://github.com/appliedzkp/zkevm-circuits/pull/293 solves the bench part

Closing this in favor of 
https://github.com/appliedzkp/halo2/issues/15 which will track optimizations.
