### ISSUE TITLE
Verify gas is indeed sufficient in success case

### ISSUE THREAD

**Issue by han0110** [appliedzkp/zkevm-circuits#68]
Currently in EVM circuit we didn't verify gas is indeed sufficient in success case. Also currently it tracks `gas_counter` as accumulated gas usage, which is not friendly to verify since we need to read out the `gas_available` of this call which we don't actually track step by step every time.

We should track `gas_left` instead and verify it's indeed sufficient in every success case naively by decode `next_state.gas_left` into 8 bytes to verify it's not underflow.

Also after `gas_left` is capped in `u64`, then everything calculated to be gas cost like `quad_memory_cost` could also be capped in 8 bytes in success case.

**Comment by spartucus** [comment]
What will happen if gas limit is bigger than `2**32` in the future? Success on L2 and  failed on L1?

**Comment by DreamWuGit** [comment]
suggest to extract  common module such as gas_counter.rs , which holds all op codes' gas counter there.  other op code gadget can refer to it . should be good modularization.
