### ISSUE TITLE
Need rust-toolchain

### ISSUE THREAD

**Issue by Lawliet-Chan** [appliedzkp/zkevm-circuits#76]
zkevm-circuits uses rust nightly, so I think we need a `rust-toolchain` file to standardize the project

**Comment by han0110** [comment]
I think right now we don't use features requiring nightly? For the stable version we are using 1.53 (stick to CI). Does the warning `can't set wrap_comments = true` from `cargo fmt` leads you think we are using nightly?

**Comment by Lawliet-Chan** [comment]
Actually, I met a bug  when I first built the code because of my old nightly version   and  I  update rustc to fix it.

Maybe our codes don't need  nightly, but we cannot guarantee  the dependent libs don't have it.   Sometimes  some library  requires a specific version of nightly.  
So  a unified version is more conducive to the standardization of the project.    `rust-toolchain` can constrain and unify the version of nightly. It is friendly to developers.

**Comment by CPerezz** [comment]
Seems fine to me! We discussed this with @han0110 and @ChihChengLiang and agreed to setup the toolchain file targeting stable and not overriting it in the CI!
