### ISSUE TITLE
bus-mapping: Implement Opcode trait for all non-storage-related `OpcodeId`s

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#83]
This will be needed in order to have the capability of testing most of the traces that we might consider.

This will probably exclude opcodes like `CALL`, `CALLDATACOPY` etc.. As they might require a bit extra config and design.

- [x] STOP https://github.com/appliedzkp/zkevm-specs/pull/100
- [x] ADD
- [x] MUL
- [x] SUB
- [x] DIV
- [x] SDIV
- [x] MOD
- [x] SMOD
- [x] ADDMOD
- [x] MULMOD
- [x] EXP
- [x] SIGNEXTEND
- [x] LT
- [x] GT
- [x] SLT
- [x] SGT
- [x] EQ
- [x] ISZERO
- [x] AND
- [x] OR
- [x] XOR
- [x] NOT
- [x] BYTE
- [ ] CALLDATALOAD `call related opcode` https://github.com/appliedzkp/zkevm-specs/pull/124 https://github.com/scroll-tech/zkevm-circuits/pull/120
- [x] CALLDATASIZE `call related opcode` https://github.com/appliedzkp/zkevm-circuits/pull/329
- [x] CALLDATACOPY `call related opcode` https://github.com/appliedzkp/zkevm-circuits/pull/297
- [ ] CODESIZE
- [ ] CODECOPY
- [x] SHL
- [x] SHR
- [x] SAR
- [x] POP 
- [x] MLOAD
- [x] MSTORE
- [x] MSTORE8
- [x] JUMP
- [x] JUMPI
- [x] PC
- [x] MSIZE
- [x] JUMPDEST
- [x] PUSH_N
- [x] DUP_N
- [x] SWAP_N
- [ ] RETURN
- [ ] REVERT
- [ ] INVALID
- [ ] SHA3
- [ ] ADDRESS
- [ ] BALANCE
- [ ] ORIGIN `tx related opcode` https://github.com/appliedzkp/zkevm-specs/issues/121
- [x] CALLER `call related opcode` https://github.com/appliedzkp/zkevm-circuits/pull/287
- [x] CALLVALUE `call related opcode` https://github.com/appliedzkp/zkevm-circuits/pull/287
- [x] GASPRICE `tx related opcode` https://github.com/appliedzkp/zkevm-specs/pull/119
- [ ] EXTCODESIZE
- [ ] EXTCODECOPY
- [ ] EXTCODEHASH
- [ ] RETURNDATASIZE
- [ ] RETURNDATACOPY
- [ ] BLOCKHASH
- [x] COINBASE `block related opcode`
- [x] TIMESTAMP `block related opcode`
- [x] NUMBER `block related opcode`
- [ ] DIFFICULTY `block related opcode`
- [x] GASLIMIT `block related opcode`
- [x] CHAINID
- [x] SELFBALANCE https://github.com/appliedzkp/zkevm-circuits/pull/328
- [ ] BASEFEE
- [x] SLOAD https://github.com/appliedzkp/zkevm-specs/pull/106 https://github.com/scroll-tech/zkevm-circuits/pull/120
- [ ] SSTORE https://github.com/appliedzkp/zkevm-specs/pull/106 https://github.com/scroll-tech/zkevm-circuits/pull/120
- [x] GAS
- [ ] LOG_N https://github.com/appliedzkp/zkevm-circuits/pull/335
- [ ] CREATE
- [ ] CREATE2
- [ ] CALL @han0110 https://github.com/appliedzkp/zkevm-circuits/pull/278
- [ ] CALLCODE
- [ ] DELEGATECALL
- [ ] STATICCALL
- [ ] SELFDESTRUCT

**Comment by CPerezz** [comment]
Even though this is assigned to me, any contribution to trait implementations is welcomed as long as is first spec'd out and approved and the impl guidelines follow the previous implemented opcodes. :smile:

**Comment by HAOYUatHZ** [comment]
+ JUMP tracked in https://github.com/scroll-tech/zkevm-circuits/pull/24
+ JUMPI tracked in https://github.com/scroll-tech/zkevm-circuits/pull/25
+ MSTORE8 covered in https://github.com/scroll-tech/zkevm-circuits/pull/25

**Comment by CPerezz** [comment]
Closing in deref to #477
