### ISSUE TITLE
Testing time too long

### ISSUE THREAD

**Issue by gaswhat** [appliedzkp/zkevm-circuits#88]
In the XOR circuit implementation (#75), I added the XOR lookup table with 2^16 rows. In order to accommodate so many rows, I need to increase the table size in Halo2 to 2^17. But after that, the testing time becomes very long. It took me more than 10 minutes to finish the test. What's worse is that after having XOR circuit, all other opcode tests need to bump up their table size. It's very likely that the Github test will timeout. We need to find a way to address this issue.

**Comment by gaswhat** [comment]
cc @therealyingtong Do you have any recommendation?

**Comment by han0110** [comment]
Ran #75 in release mode cost me 6 minutes. The most costly part in `verify` is when collecting `gate_errors`, which iterates over the whole circuit (`2**18` in #75's case) and costs 271 seconds.

Maybe we can add a flag `lazy_eval` to `MockProver` to only verify gate constraint on `usable_rows` just like it does when verify lookup. But there is also risk that some edge case of gate constraint will be hide. Do you think it's safe to do so? @therealyingtong 

The second costly part is when collecting `lookup_errors`, which iterates only the `usable_rows` and cost 55 seconds, which might be the next target to tune.

**Comment by therealyingtong** [comment]
i've also run into this problem before, and will take a closer look at the MockProver and @han0110's suggestion.

for now, we could `#[ignore]` expensive tests, and run them locally without tripping up CI.

**Comment by ChihChengLiang** [comment]
I tried a way to apply  #135  and zcash/halo2#389 in a special way, but the test is way slower that I didn't see it ends. 

1. First change the halo2 version to your local fork `halo2 = {path="../../halo2"}` in Cargo.toml.
2. Go to your local fork and checkout to `4283713ec76051eaf21a06d0279fa7d3497cafb6`, which is what `zkevm-circuits` currently use now.
3. `git fetch` to get the latest version of halo2 and run `git cherry-pick b94aab76a338870fec778d4da3a1c6789bc92bc4` (the zcash/halo2#389 commit) to apply 

The reason not doing a full upgrade in halo2 is that it needs to change many other parts of the codebase.
